import {
  HEAVY_SPRING_D,
  HEAVY_SPRING_K,
  SNAPPY_SPRING_D,
  SNAPPY_SPRING_K,
  hold,
  step,
} from './motion.ts'
import {
  SCENE_FPS,
  SCENE_HEIGHT,
  SCENE_WIDTH,
  type Layer,
  type Scene,
  type TextLayer,
} from './scene.ts'

const BG = '#0c0c0e'
const INK = '#f4f1ea'
const MUTED = '#8a867c'
const ACCENT = '#d6ff3d'

function text(partial: Omit<TextLayer, 'kind'>): TextLayer {
  return { kind: 'text', align: 'left', ...partial }
}

export const SAMPLE_PROMPTS = [
  {
    id: 'showreel',
    label: 'Showreel',
    prompt:
      'make a dynamic 8-second motion graphics video that shows what an incredible motion designer you are, like it\'s your showreel for a résumé. go all out.',
  },
  {
    id: 'launch',
    label: 'Product launch',
    prompt:
      'Make a dynamic 7-second motion graphics video for Motion Studio, with the energy of a motion designer\'s showreel. Hook: TOO SLOW. One accent #d6ff3d.',
  },
  {
    id: 'beat',
    label: 'Beat grid',
    prompt:
      '8-second 16:9 beat-grid film at 120 BPM. Cells pulse on the grid, playhead travels, type says 120 BPM. Springs only.',
  },
  {
    id: 'lockup',
    label: 'Logo lockup',
    prompt:
      '5-second logo lockup for "OPUS". Heavy spring on the wordmark, accent rule, tagline CODE TO FILM. #d6ff3d.',
  },
] as const

export function showreelScene(): Scene {
  const letters = ['M', 'O', 'T', 'I', 'O', 'N']
  const letterLayers: Layer[] = letters.map((ch, i) => {
    const at = 0.08 + i * 0.055
    return text({
      id: `hook-${ch}-${i}`,
      from: 0,
      to: 2.35,
      text: ch,
      x: hold(210 + i * 145),
      y: step(at, 430, 352, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
      scale: step(at, 0.42, 1, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
      fontSize: 168,
      fontWeight: 700,
      font: 'display',
      fill: INK,
      tracking: -4,
    })
  })

  return {
    id: 'showreel',
    title: 'Showreel',
    width: SCENE_WIDTH,
    height: SCENE_HEIGHT,
    fps: SCENE_FPS,
    duration: 8,
    background: BG,
    accent: ACCENT,
    ink: INK,
    grain: 0.08,
    camera: {
      zoom: { keys: [[0, 1.08], [0.15, 1], [4.35, 1], [4.5, 1.04], [4.7, 1]], k: 140, d: 22 },
      x: hold(0),
      y: hold(0),
      rotate: hold(0),
    },
    shots: [
      { t: 0, label: 'HOOK' },
      { t: 2.3, label: 'CONTRACT' },
      { t: 4.4, label: 'SPRING' },
      { t: 6.3, label: 'LOCKUP' },
    ],
    layers: [
      text({
        id: 'shot-1',
        from: 0,
        to: 2.35,
        text: '01  HOOK',
        x: step(0.02, 40, 72, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
        y: hold(72),
        fontSize: 18,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        tracking: 4,
      }),
      ...letterLayers,
      {
        kind: 'rule',
        id: 'hook-rule',
        from: 0,
        to: 2.35,
        x: step(0.28, 0, 210, 200, 24),
        y: hold(448),
        w: step(0.28, 0, 860, 200, 24),
        h: 10,
        fill: ACCENT,
      },
      text({
        id: 'shot-2',
        from: 2.3,
        to: 4.45,
        text: '02  CONTRACT',
        x: step(2.32, 40, 72),
        y: hold(72),
        fontSize: 18,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        tracking: 4,
      }),
      text({
        id: 'seek',
        from: 2.3,
        to: 4.45,
        text: 'seek(t)',
        x: hold(72),
        y: step(2.38, 400, 318, HEAVY_SPRING_K, HEAVY_SPRING_D),
        scale: step(2.38, 0.7, 1, HEAVY_SPRING_K, HEAVY_SPRING_D),
        fontSize: 148,
        fontWeight: 500,
        font: 'mono',
        fill: INK,
      }),
      text({
        id: 'seek-sub',
        from: 2.3,
        to: 4.45,
        text: 'window.seek = (t) => draw(t)',
        x: step(2.55, 40, 76),
        y: hold(430),
        fontSize: 22,
        fontWeight: 400,
        font: 'mono',
        fill: MUTED,
      }),
      {
        kind: 'ticks',
        id: 'ticks',
        from: 2.3,
        to: 4.45,
        y: 560,
        count: 33,
        fill: INK,
        playhead: true,
      },
      text({
        id: 'shot-3',
        from: 4.4,
        to: 6.35,
        text: '03  SPRING',
        x: step(4.42, 40, 72),
        y: hold(72),
        fontSize: 18,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        tracking: 4,
      }),
      ...(['SPRING', 'BEAT', 'LOCK'] as const).flatMap((word, i) => {
        const at = 4.5 + i * 0.12
        const y = 168 + i * 150
        return [
          {
            kind: 'box' as const,
            id: `chip-bg-${word}`,
            from: 4.4,
            to: 6.35,
            x: step(at, 40, 72, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
            y: hold(y),
            w: hold(420),
            h: hold(128),
            r: 8,
            fill: i === 1 ? ACCENT : '#18181b',
            scale: step(at, 0.82, 1, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
          },
          text({
            id: `chip-${word}`,
            from: 4.4,
            to: 6.35,
            text: word,
            x: step(at, 70, 100, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
            y: hold(y + 64),
            fontSize: 56,
            fontWeight: 700,
            font: 'display',
            fill: i === 1 ? '#111111' : INK,
          }),
        ]
      }),
      text({
        id: 'shot-4',
        from: 6.3,
        to: 8,
        text: '04  LOCKUP',
        x: step(6.32, 40, 72),
        y: hold(72),
        fontSize: 18,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        tracking: 4,
      }),
      text({
        id: 'opus',
        from: 6.3,
        to: 8,
        text: 'OPUS',
        x: hold(SCENE_WIDTH / 2),
        y: step(6.4, 400, 310, HEAVY_SPRING_K, HEAVY_SPRING_D),
        scale: step(6.4, 0.55, 1, HEAVY_SPRING_K, HEAVY_SPRING_D),
        fontSize: 120,
        fontWeight: 700,
        font: 'display',
        fill: INK,
        align: 'center',
      }),
      text({
        id: 'studio',
        from: 6.3,
        to: 8,
        text: 'STUDIO',
        x: hold(SCENE_WIDTH / 2),
        y: step(6.55, 430, 412, 160, 22),
        fontSize: 28,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        align: 'center',
        tracking: 14,
      }),
      {
        kind: 'rule',
        id: 'lock-rule',
        from: 6.3,
        to: 8,
        x: step(6.6, SCENE_WIDTH / 2, SCENE_WIDTH / 2 - 140, 180, 22),
        y: hold(456),
        w: step(6.6, 0, 280, 180, 22),
        h: 6,
        fill: ACCENT,
      },
      text({
        id: 'cta',
        from: 6.3,
        to: 8,
        text: 'CODE  →  FRAMES  →  FILM',
        x: hold(SCENE_WIDTH / 2),
        y: step(6.75, 520, 510),
        fontSize: 16,
        fontWeight: 500,
        font: 'mono',
        fill: MUTED,
        align: 'center',
        tracking: 3,
      }),
    ],
  }
}

export function launchScene(title = 'MOTION STUDIO'): Scene {
  const word = title.toUpperCase().slice(0, 22)
  return {
    id: 'launch',
    title: 'Product launch',
    width: SCENE_WIDTH,
    height: SCENE_HEIGHT,
    fps: SCENE_FPS,
    duration: 7,
    background: BG,
    accent: ACCENT,
    ink: INK,
    grain: 0.07,
    camera: {
      zoom: { keys: [[0, 1.06], [0.2, 1], [3.3, 1], [3.45, 1.05], [3.7, 1]], k: 150, d: 22 },
      x: hold(0),
      y: hold(0),
      rotate: hold(0),
    },
    shots: [
      { t: 0, label: 'PROBLEM' },
      { t: 1.7, label: 'ASSEMBLE' },
      { t: 3.5, label: 'METRIC' },
      { t: 5.2, label: 'CTA' },
    ],
    layers: [
      text({
        id: 'prob-label',
        from: 0,
        to: 1.75,
        text: 'THE BRIEF',
        x: step(0.04, 40, 72),
        y: hold(80),
        fontSize: 16,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        tracking: 6,
      }),
      text({
        id: 'too-slow',
        from: 0,
        to: 1.75,
        text: 'TOO SLOW',
        x: hold(72),
        y: step(0.1, 420, 340, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
        scale: step(0.1, 0.6, 1, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
        fontSize: 132,
        fontWeight: 700,
        font: 'display',
        fill: INK,
      }),
      {
        kind: 'rule',
        id: 'strike',
        from: 0,
        to: 1.75,
        x: step(0.45, 72, 72, 220, 22),
        y: hold(338),
        w: step(0.45, 0, 640, 220, 22),
        h: 8,
        fill: ACCENT,
      },
      ...(['CAPTURE', 'SEEK(T)', 'ENCODE'].map((word, i) => {
        const at = 1.78 + i * 0.1
        return text({
          id: `feat-${word}`,
          from: 1.7,
          to: 3.55,
          text: word,
          x: step(at, 40, 80 + i * 20, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
          y: hold(200 + i * 140),
          scale: step(at, 0.7, 1, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
          fontSize: 86,
          fontWeight: 700,
          font: 'display',
          fill: i === 1 ? ACCENT : INK,
        })
      })),
      text({
        id: 'metric',
        from: 3.5,
        to: 5.25,
        text: '12×',
        x: hold(SCENE_WIDTH / 2),
        y: step(3.58, 400, 300, HEAVY_SPRING_K, HEAVY_SPRING_D),
        scale: step(3.58, 0.4, 1, HEAVY_SPRING_K, HEAVY_SPRING_D),
        fontSize: 220,
        fontWeight: 700,
        font: 'display',
        fill: ACCENT,
        align: 'center',
      }),
      text({
        id: 'metric-sub',
        from: 3.5,
        to: 5.25,
        text: 'FASTER REELS',
        x: hold(SCENE_WIDTH / 2),
        y: step(3.85, 500, 468),
        fontSize: 28,
        fontWeight: 500,
        font: 'mono',
        fill: INK,
        align: 'center',
        tracking: 10,
      }),
      text({
        id: 'brand',
        from: 5.2,
        to: 7,
        text: word,
        x: hold(SCENE_WIDTH / 2),
        y: step(5.3, 400, 320, HEAVY_SPRING_K, HEAVY_SPRING_D),
        scale: step(5.3, 0.6, 1, HEAVY_SPRING_K, HEAVY_SPRING_D),
        fontSize: word.length > 14 ? 56 : 72,
        fontWeight: 700,
        font: 'display',
        fill: INK,
        align: 'center',
      }),
      {
        kind: 'rule',
        id: 'cta-rule',
        from: 5.2,
        to: 7,
        x: step(5.5, SCENE_WIDTH / 2, SCENE_WIDTH / 2 - 90),
        y: hold(380),
        w: step(5.5, 0, 180),
        h: 6,
        fill: ACCENT,
      },
      text({
        id: 'cta',
        from: 5.2,
        to: 7,
        text: 'SHIP THE REEL',
        x: hold(SCENE_WIDTH / 2),
        y: step(5.65, 460, 430),
        fontSize: 22,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        align: 'center',
        tracking: 8,
      }),
    ],
  }
}

export function beatScene(): Scene {
  return {
    id: 'beat',
    title: 'Beat grid',
    width: SCENE_WIDTH,
    height: SCENE_HEIGHT,
    fps: SCENE_FPS,
    duration: 8,
    background: BG,
    accent: ACCENT,
    ink: INK,
    grain: 0.06,
    camera: {
      zoom: hold(1),
      x: hold(0),
      y: hold(0),
      rotate: hold(0),
    },
    shots: [
      { t: 0, label: 'GRID' },
      { t: 2, label: 'DOWNBEAT' },
      { t: 4, label: 'TYPE' },
      { t: 6, label: 'LOCK' },
    ],
    layers: [
      {
        kind: 'cells',
        id: 'grid',
        from: 0,
        to: 8,
        x: 72,
        y: 150,
        cols: 8,
        rows: 3,
        size: 118,
        gap: 18,
        bpm: 120,
        fill: INK,
        accent: ACCENT,
      },
      text({
        id: 'bpm',
        from: 0,
        to: 8,
        text: '120 BPM',
        x: hold(72),
        y: step(0.08, 80, 64, SNAPPY_SPRING_K, SNAPPY_SPRING_D),
        fontSize: 22,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        tracking: 6,
      }),
      text({
        id: 'grid-title',
        from: 3.8,
        to: 8,
        text: 'ON THE GRID',
        x: hold(72),
        y: step(4.0, 680, 640, HEAVY_SPRING_K, HEAVY_SPRING_D),
        fontSize: 48,
        fontWeight: 700,
        font: 'display',
        fill: INK,
      }),
      {
        kind: 'ticks',
        id: 'ruler',
        from: 0,
        to: 8,
        y: 580,
        count: 33,
        fill: INK,
        playhead: true,
      },
    ],
  }
}

export function lockupScene(wordmark = 'OPUS'): Scene {
  const word = wordmark.toUpperCase().slice(0, 12)
  const letters = word.split('')
  const letterW = Math.min(120, 900 / Math.max(letters.length, 1))
  const startX = SCENE_WIDTH / 2 - ((letters.length - 1) * letterW) / 2

  return {
    id: 'lockup',
    title: 'Logo lockup',
    width: SCENE_WIDTH,
    height: SCENE_HEIGHT,
    fps: SCENE_FPS,
    duration: 5,
    background: BG,
    accent: ACCENT,
    ink: INK,
    grain: 0.07,
    camera: {
      zoom: { keys: [[0, 1.1], [0.2, 1]], k: HEAVY_SPRING_K, d: HEAVY_SPRING_D },
      x: hold(0),
      y: hold(0),
      rotate: hold(0),
    },
    shots: [
      { t: 0, label: 'MARK' },
      { t: 2.4, label: 'TAG' },
    ],
    layers: [
      ...letters.map((ch, i) => {
        const at = 0.1 + i * 0.07
        return text({
          id: `letter-${i}`,
          from: 0,
          to: 5,
          text: ch,
          x: hold(startX + i * letterW),
          y: step(at, 420, 330, HEAVY_SPRING_K, HEAVY_SPRING_D),
          scale: step(at, 0.3, 1, HEAVY_SPRING_K, HEAVY_SPRING_D),
          fontSize: letterW + 20,
          fontWeight: 700,
          font: 'display',
          fill: INK,
          align: 'center',
        })
      }),
      {
        kind: 'rule',
        id: 'mark-rule',
        from: 0,
        to: 5,
        x: step(1.1, SCENE_WIDTH / 2, SCENE_WIDTH / 2 - 160, 140, 20),
        y: hold(400),
        w: step(1.1, 0, 320, 140, 20),
        h: 8,
        fill: ACCENT,
      },
      text({
        id: 'tag',
        from: 2.2,
        to: 5,
        text: 'CODE TO FILM',
        x: hold(SCENE_WIDTH / 2),
        y: step(2.35, 480, 448),
        fontSize: 20,
        fontWeight: 500,
        font: 'mono',
        fill: ACCENT,
        align: 'center',
        tracking: 10,
      }),
    ],
  }
}

export const SAMPLE_BUILDERS: Record<string, (title?: string) => Scene> = {
  showreel: () => showreelScene(),
  launch: (title) => launchScene(title),
  beat: () => beatScene(),
  lockup: (title) => lockupScene(title),
}
