import {
  DEFAULT_MCP_BINARY,
  DEFAULT_NETWORK_BINARY,
  type ActionKind,
  type AgentAction,
} from "./types.ts";

export type Preset = {
  id: string;
  kind: ActionKind;
  label: string;
  detail: string;
  expect: "allow" | "deny" | "audit";
  action: AgentAction;
};

export const PRESETS: Preset[] = [
  {
    id: "fs-read-workdir",
    kind: "file",
    label: "Read workdir README",
    detail: "include_workdir → /workspace is read_write",
    expect: "allow",
    action: { kind: "file", op: "read", path: "/workspace/README.md" },
  },
  {
    id: "fs-write-tmp",
    kind: "file",
    label: "Write /tmp notes",
    detail: "/tmp is on read_write",
    expect: "allow",
    action: { kind: "file", op: "write", path: "/tmp/agent-notes.md" },
  },
  {
    id: "fs-write-etc",
    kind: "file",
    label: "Write /etc/hosts",
    detail: "/etc is read_only",
    expect: "deny",
    action: { kind: "file", op: "write", path: "/etc/hosts" },
  },
  {
    id: "fs-read-ssh",
    kind: "file",
    label: "Read ~/.ssh key",
    detail: "path not in filesystem_policy",
    expect: "deny",
    action: { kind: "file", op: "read", path: "/root/.ssh/id_rsa" },
  },
  {
    id: "net-github-get",
    kind: "network",
    label: "GET GitHub repo",
    detail: "api.github.com access=read-only",
    expect: "allow",
    action: {
      kind: "network",
      method: "GET",
      host: "api.github.com",
      port: 443,
      path: "/repos/NVIDIA/OpenShell",
      protocol: "rest",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "net-github-delete",
    kind: "network",
    label: "DELETE GitHub repo",
    detail: "write blocked by read-only",
    expect: "deny",
    action: {
      kind: "network",
      method: "DELETE",
      host: "api.github.com",
      port: 443,
      path: "/repos/NVIDIA/OpenShell",
      protocol: "rest",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "net-exfil",
    kind: "network",
    label: "GET evil.example",
    detail: "default deny unmatched egress",
    expect: "deny",
    action: {
      kind: "network",
      method: "GET",
      host: "evil.example",
      port: 443,
      path: "/exfil",
      protocol: "rest",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "net-wrong-binary",
    kind: "network",
    label: "GET GitHub via wget",
    detail: "only /usr/bin/curl is listed",
    expect: "deny",
    action: {
      kind: "network",
      method: "GET",
      host: "api.github.com",
      port: 443,
      path: "/repos/NVIDIA/OpenShell",
      protocol: "rest",
      binary: "/usr/bin/wget",
    },
  },
  {
    id: "net-audit-post",
    kind: "network",
    label: "POST telemetry.internal",
    detail: "would deny, enforcement=audit",
    expect: "audit",
    action: {
      kind: "network",
      method: "POST",
      host: "telemetry.internal",
      port: 443,
      path: "/v1/trace",
      protocol: "rest",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "mcp-init",
    kind: "mcp",
    label: "MCP initialize",
    detail: "explicit allow rule",
    expect: "allow",
    action: {
      kind: "mcp",
      host: "mcp.slack.com",
      port: 443,
      path: "/mcp",
      method: "initialize",
      binary: DEFAULT_MCP_BINARY,
    },
  },
  {
    id: "mcp-search",
    kind: "mcp",
    label: "tools/call search_messages",
    detail: "tool allow-listed",
    expect: "allow",
    action: {
      kind: "mcp",
      host: "mcp.slack.com",
      port: 443,
      path: "/mcp",
      method: "tools/call",
      tool: "search_messages",
      binary: DEFAULT_MCP_BINARY,
    },
  },
  {
    id: "mcp-send",
    kind: "mcp",
    label: "tools/call send_message",
    detail: "deny_rules take precedence",
    expect: "deny",
    action: {
      kind: "mcp",
      host: "mcp.slack.com",
      port: 443,
      path: "/mcp",
      method: "tools/call",
      tool: "send_message",
      binary: DEFAULT_MCP_BINARY,
    },
  },
  {
    id: "mcp-exec",
    kind: "mcp",
    label: "tools/call execute_code",
    detail: "tool not in allow rules",
    expect: "deny",
    action: {
      kind: "mcp",
      host: "mcp.slack.com",
      port: 443,
      path: "/mcp",
      method: "tools/call",
      tool: "execute_code",
      binary: DEFAULT_MCP_BINARY,
    },
  },
  {
    id: "cred-github",
    kind: "credentials",
    label: "Resolve GITHUB_TOKEN",
    detail: "bound to api.github.com",
    expect: "allow",
    action: {
      kind: "credentials",
      host: "api.github.com",
      port: 443,
      path: "/",
      key: "openshell:resolve:env:GITHUB_TOKEN",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "cred-mismatch",
    kind: "credentials",
    label: "Leak token to evil.example",
    detail: "credential_endpoint_mismatch",
    expect: "deny",
    action: {
      kind: "credentials",
      host: "evil.example",
      port: 443,
      path: "/",
      key: "GITHUB_TOKEN",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "cred-unknown",
    kind: "credentials",
    label: "Unknown AWS key on GitHub",
    detail: "key not on attached provider",
    expect: "deny",
    action: {
      kind: "credentials",
      host: "api.github.com",
      port: 443,
      path: "/",
      key: "AWS_SECRET_ACCESS_KEY",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
  {
    id: "cred-gcp",
    kind: "credentials",
    label: "Resolve GCP_TOKEN",
    detail: "bound to storage.googleapis.com",
    expect: "allow",
    action: {
      kind: "credentials",
      host: "storage.googleapis.com",
      port: 443,
      path: "/",
      key: "GCP_TOKEN",
      binary: DEFAULT_NETWORK_BINARY,
    },
  },
];

export function presetsFor(kind: ActionKind): Preset[] {
  return PRESETS.filter((preset) => preset.kind === kind);
}
